name: C/C++ Benchmark

on:
  push:
    branches: [ "benchmark" ]
  pull_request:
    branches: [ "benchmark" ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: 
      image: 444047485/kuipercourse_env:v1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: env-cache-install
        key: env-cache-install-20230303
    - name: Compile and Test 
      run: mkdir build && cd build && cmake .. && make -j12 
    - name: Test
      run: cd bin && ./test_kuiper_course
    - name: Run benchmark
      run: cd bin && ./benchmark_kuiper_course --benchmark_format=json --benchmark_out=benchmark_result.json

  
