name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: 0 2 * * 1-5
jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: 444047485/kuipercourse_env:v1.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master 
    - name: Compile and Test 
      run: mkdir build && cd build && cmake .. && make -j8 && ../bin/test_kuiper_course
