name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: 444047485/kuipercourse_env:v1.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master 
    - name: make
      run: echo "HELLO"
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
