name: up_subscription
on:
  schedule:
  - cron: 0 2 * * 1-5
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: 444047485/kuipercourse_env:v1.0
    steps:
    - name: Script
      run: bash u[date_vpn.sh
