name: Update VPN

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: 444047485/kuipercourse_env:v1.0

    steps:
    - name: Update VPN
      run: bash vpn.sh
